"use client"

import React, { createContext, useContext, useState, useEffect } from 'react'

type Language = 'ar' | 'en'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
  isRTL: boolean
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Translation dictionary
const translations = {
  ar: {
    // Landing page
    'landing.title': 'PROMOXA',
    'landing.subtitle': 'منصة العملات الرقمية المتقدمة',
    'landing.description': 'انضم إلى مجتمعنا واحصل على أرباح يومية من خلال المهام البسيطة',
    'landing.features.title': 'المميزات',
    'landing.features.daily': 'أرباح يومية',
    'landing.features.referral': 'نظام إحالة متقدم',
    'landing.features.support': 'دعم 24/7',
    'landing.features.secure': 'أمان عالي',
    'landing.getStarted': 'ابدأ الآن',
    'landing.login': 'تسجيل الدخول',
    'landing.register': 'إنشاء حساب',
    
    // Home page
    'home.title': 'الرئيسية',
    'home.welcome': 'مرحباً بك في PROMOXA',
    'home.totalBalance': 'الرصيد المتاح',
    'home.totalProfit': 'إجمالي الأرباح',
    'home.frozenBalance': 'المبلغ المجمد',
    'home.referralEarnings': 'أرباح الإحالة',
    'home.dailyEarnings': 'أرباح اليوم',
    'home.totalEarnings': 'إجمالي الأرباح',
    'home.startDailyTasks': 'ابدأ المهام اليومية الآن',
    'home.operations': 'العمليات',
    'home.orders': 'الطلبات اليومية',
    'home.withdraw': 'السحب',
    'home.deposit': 'الإيداع',
    'home.team': 'الفريق',
    'home.support': 'الدعم',
    'home.promoCode': 'الكود الترويجي',
    'home.plans': 'الخطط',
    'home.community': 'المجتمع',
    'home.news': 'آخر الأخبار',
    'home.news.feature': 'تم إطلاق ميزة جديدة للمجتمع',
    'home.news.update': 'تحديث النظام لتحسين الأداء',
    'home.news.offers': 'عروض خاصة للخطة الذهبية',
    'home.news.2hoursAgo': 'منذ ساعتين',
    'home.news.1dayAgo': 'منذ يوم واحد',
    'home.news.3daysAgo': 'منذ 3 أيام',
    'home.referralCode': 'كود الإحالة',
    'home.copySuccess': 'تم النسخ!',
    'home.demoMode': 'أنت في الوضع التجريبي - البيانات غير حقيقية',
    'home.loading': 'جاري تحميل البيانات...',
    'home.user': 'المستخدم',
    'home.back': 'العودة',
    'home.logout': 'تسجيل الخروج',
    'home.notifications': 'الإشعارات',
    'home.language': 'اللغة',
    'home.profile': 'الملف الشخصي',
    
    // Auth pages
    'auth.login': 'تسجيل الدخول',
    'auth.register': 'إنشاء حساب',
    'auth.logout': 'تسجيل الخروج',
    'auth.username': 'اسم المستخدم',
    'auth.usernameOrPhone': 'اسم المستخدم أو رقم الهاتف',
    'auth.password': 'كلمة المرور',
    'auth.confirmPassword': 'تأكيد كلمة المرور',
    'auth.email': 'البريد الإلكتروني',
    'auth.phone': 'رقم الهاتف',
    'auth.fullName': 'الاسم الكامل',
    'auth.forgotPassword': 'نسيت كلمة المرور؟',
    'auth.noAccount': 'ليس لديك حساب؟',
    'auth.haveAccount': 'لديك حساب بالفعل؟',
    'auth.createAccount': 'إنشاء حساب جديد',
    'auth.loginToAccount': 'تسجيل الدخول إلى حسابك',
    'auth.registerAccount': 'إنشاء حساب جديد',
    'auth.loginSuccess': 'تم تسجيل الدخول بنجاح',
    'auth.loginError': 'فشل في تسجيل الدخول',
    'auth.registerSuccess': 'تم إنشاء الحساب بنجاح',
    'auth.registerError': 'فشل في إنشاء الحساب',
    'auth.passwordsNotMatch': 'كلمات المرور غير متطابقة',
    'auth.invalidCredentials': 'بيانات غير صحيحة',
    'auth.serverError': 'خطأ في الخادم',
    'auth.networkError': 'خطأ في الاتصال',
    'auth.demoMode': 'الوضع التجريبي',
    'auth.demoDescription': 'الخادم الخلفي غير متاح حالياً. يمكنك تجربة الواجهة الأمامية في الوضع التجريبي.',
    'auth.tryDemo': 'تجربة الوضع التجريبي',
    'auth.enterUsername': 'أدخل اسم المستخدم أو رقم الهاتف',
    'auth.enterPassword': 'أدخل كلمة المرور',
    'auth.enterEmail': 'أدخل البريد الإلكتروني',
    'auth.enterPhone': 'أدخل رقم الهاتف',
    'auth.enterFullName': 'أدخل الاسم الكامل',
    'auth.enterConfirmPassword': 'أدخل تأكيد كلمة المرور',
    'auth.loginButton': 'تسجيل الدخول',
    'auth.registerButton': 'إنشاء حساب',
    'auth.loggingIn': 'جاري تسجيل الدخول...',
    'auth.registering': 'جاري إنشاء الحساب...',
    
    // Forgot Password page
    'forgotPassword.title': 'إعادة تعيين كلمة المرور',
    'forgotPassword.enterEmailDescription': 'أدخل بريدك الإلكتروني لإرسال رمز التحقق',
    'forgotPassword.email': 'البريد الإلكتروني',
    'forgotPassword.enterEmail': 'أدخل بريدك الإلكتروني',
    'forgotPassword.sendOtp': 'إرسال رمز التحقق',
    'forgotPassword.sending': 'جاري الإرسال...',
    'forgotPassword.sentSuccessfully': 'تم الإرسال بنجاح!',
    'forgotPassword.otpSentMessage': 'تم إرسال رمز التحقق إلى بريدك الإلكتروني',
    'forgotPassword.tryAgain': 'إعادة المحاولة',
    'forgotPassword.backToLogin': 'العودة لتسجيل الدخول',
    'forgotPassword.importantInfo': 'معلومات مهمة',
    'forgotPassword.info1Email': 'تأكد من إدخال البريد الإلكتروني المسجل في حسابك',
    'forgotPassword.info2Otp': 'رمز التحقق صالح لمدة 10 دقائق فقط',
    'forgotPassword.info3Email': 'إذا لم تستلم الرمز، تحقق من مجلد الرسائل غير المرغوب فيها',
    'forgotPassword.info4': 'للمساعدة الإضافية، تواصل مع الدعم الفني',
    
    // Orders page
    'orders.title': 'الطلبات اليومية',
    'orders.status': 'حالة المهام اليومية',
    'orders.completed': 'مكتملة',
    'orders.progress': 'التقدم',
    'orders.openTime': 'وقت فتح المهام',
    'orders.openTimeDesc': 'تفتح المهام اليومية الساعة 7:00 مساءً بتوقيت السيرفر',
    'orders.completeTask': 'إكمال المهمة',
    'orders.complete': 'إكمال',
    'orders.taskCompleted': 'تم إكمال المهمة بنجاح!',
    'orders.completing': 'جاري الإكمال...',
    'orders.noTasks': 'لا توجد مهام متاحة',
    'orders.noTasksDesc': 'لا توجد مهام متاحة حالياً. تحقق لاحقاً للحصول على مهام جديدة.',
    'orders.closedDesc': 'المهام مغلقة حالياً. تفتح الساعة 7:00 مساءً بتوقيت السيرفر.',
    'orders.loading': 'جاري تحميل المهام...',
    'orders.error': 'حدث خطأ أثناء تحميل المهام',
    'orders.success': 'تم إكمال المهمة بنجاح!',
    'orders.failed': 'فشل في إكمال المهمة',
    'orders.open': 'مفتوحة',
    'orders.closed': 'مغلقة',
    'orders.taskTitle': 'عنوان المهمة',
    'orders.taskDescription': 'وصف المهمة',
    'orders.taskProfit': 'ربح المهمة',
    'orders.infoTitle': 'معلومات مهمة',
    'orders.infoDesc1': 'تفتح المهام اليومية الساعة 7:00 مساءً بتوقيت السيرفر',
    'orders.infoDesc2': '5 مهام يومية لكل مستخدم',
    'orders.infoDesc3': 'بعد إتمام جميع المهام، تتعطل الأزرار حتى اليوم التالي',
    'orders.infoDesc4': 'قائمة المهام تحدث أسبوعياً',
    'orders.infoDesc5': 'الأرباح تضاف فوراً إلى رصيدك',
    'orders.infoDesc6': 'تتحدث المهام يومياً الساعة 7:00 صباحاً',
    'orders.today': 'اليوم',
    'orders.todayTasks': 'مهام اليوم',
    'orders.thisWeek': 'هذا الأسبوع',
    'orders.noTasksToday': 'لا توجد مهام مكتملة اليوم',
    'orders.noTasksThisWeek': 'لا توجد مهام مكتملة هذا الأسبوع',
    'orders.totalEarnings': 'إجمالي الأرباح',
    'orders.noPlanTitle': 'لا توجد خطة نشطة',
    'orders.noPlanMessage': 'يجب عليك شراء خطة للوصول إلى المهام اليومية',
    'orders.getPlan': 'احصل على خطة',
    
    // Task Descriptions - Arabic translations
    'task.description.1': 'لقد دعمت حملة تسويقية لمتجر إلكتروني.',
    'task.description.2': 'لقد روجت لتطبيق جوال جديد.',
    'task.description.3': 'لقد ساهمت في مشروع الطاقة المتجددة.',
    'task.description.4': 'لقد ساعدت في تعزيز حملة إعلانية إلكترونية.',
    'task.description.5': 'لقد شاركت في ترويج وسائل التواصل الاجتماعي.',
    'task.description.6': 'لقد ساعدت في إطلاق متجر إلكتروني جديد.',
    'task.description.7': 'لقد دعمت حملة إعلانية لمؤثر.',
    'task.description.8': 'لقد ساعدت في الإعلان عن منتجات صديقة للبيئة.',
    'task.description.9': 'لقد ساهمت في التسويق الرقمي لشركة ناشئة.',
    'task.description.10': 'لقد روجت لمنصة تعليمية إلكترونية.',
    'task.description.11': 'لقد دعمت حملة توعية لإعادة التدوير.',
    'task.description.12': 'لقد عززت حملة إعلانية لعلامة ملابس تجارية.',
    'task.description.13': 'لقد روجت لمنصة ألعاب إلكترونية.',
    'task.description.14': 'لقد ساعدت في حملة مشروع عملات رقمية.',
    'task.description.15': 'لقد دعمت حملة لوكالة سفر.',
    'task.description.16': 'لقد روجت لتطبيق توصيل طعام جديد.',
    'task.description.17': 'لقد عززت التسويق لعلامة لياقة بدنية.',
    'task.description.18': 'لقد ساهمت في إعلان للإلكترونيات.',
    'task.description.19': 'لقد روجت لحملة لأجهزة المنزل الذكي.',
    'task.description.20': 'لقد دعمت حملة تمويل للشركات الناشئة.',
    'task.description.21': 'لقد عززت دفعة تسويقية للخدمات الرقمية.',
    'task.description.22': 'لقد ساعدت في الترويج للزراعة المستدامة.',
    'task.description.23': 'لقد ساعدت في الإعلان عن منتجات أزياء جديدة.',
    'task.description.24': 'لقد دعمت مشروع استثمار إلكتروني.',
    'task.description.25': 'لقد روجت لخدمة اشتراك جديدة.',
    'task.description.26': 'لقد عززت حركة المرور لحملة تعليمية.',
    'task.description.27': 'لقد ساهمت في حملة إعلانية للطاقة الخضراء.',
    'task.description.28': 'لقد روجت لجهاز تقني مبتكر.',
    'task.description.29': 'لقد ساعدت في نمو منصة تجارة إلكترونية.',
    'task.description.30': 'لقد دعمت التوعية الإلكترونية لأمن البيانات.',
    'task.description.31': 'لقد عززت ظهور مبادرة خيرية.',
    'task.description.32': 'لقد روجت لمنصة أعمال فنية رقمية.',
    'task.description.33': 'لقد ساعدت في نشر تطبيق للمستقلين.',
    'task.description.34': 'لقد دعمت حملة للمدفوعات المحمولة.',
    'task.description.35': 'لقد روجت لحلول مصرفية رقمية جديدة.',
    'task.description.36': 'لقد عززت ترويج لمنتجات الرعاية الصحية.',
    'task.description.37': 'لقد دعمت التسويق الإلكتروني للفنانين الموسيقيين.',
    'task.description.38': 'لقد روجت لمنصة نشر الكتب.',
    'task.description.39': 'لقد ساعدت في الإعلان عن شركة SaaS.',
    'task.description.40': 'لقد ساهمت في نشر دورة إلكترونية جديدة.',
    'task.description.41': 'لقد روجت لحملة توعية للمياه النظيفة.',
    'task.description.42': 'لقد دعمت حملة لأزياء صديقة للبيئة.',
    'task.description.43': 'لقد ساعدت في حملة إعلانية للمحافظ الرقمية.',
    'task.description.44': 'لقد عززت التسويق لأداة الذكاء الاصطناعي.',
    'task.description.45': 'لقد روجت لحملة تمويل جماعي لشركة ناشئة.',
    'task.description.46': 'لقد دعمت ظهور العلامة التجارية لعلامة طعام.',
    'task.description.47': 'لقد روجت لإعلان لمعدات رياضية.',
    'task.description.48': 'لقد ساعدت في تعزيز مشروع خيري إلكتروني.',
    'task.description.49': 'لقد ساهمت في إطلاق منتج جديد.',
    'task.description.50': 'لقد دعمت حملة لخدمات الحوسبة السحابية.',
    
    // Plans page
    'plans.title': 'خطط الاستثمار',
    'plans.description': 'اختر الخطة المناسبة لك وابدأ في الاستثمار',
    'plans.basic': 'الخطة الأساسية',
    'plans.silver': 'الخطة الفضية',
    'plans.gold': 'الخطة الذهبية',
    'plans.diamond': 'الخطة الماسية',
    'plans.price': 'السعر',
    'plans.dailyProfit': 'الربح اليومي',
    'plans.duration': 'المدة',
    'plans.features': 'المميزات',
    'plans.buyNow': 'اشتر الآن',
    'plans.purchasing': 'جاري الشراء...',
    'plans.success': 'تم شراء الخطة بنجاح!',
    'plans.error': 'فشل في شراء الخطة',
    'plans.loading': 'جاري تحميل الخطط...',
    'plans.days': 'أيام',
    'plans.min': 'الحد الأدنى',
    'plans.max': 'الحد الأقصى',
    'plans.usdt': 'USDT',
    'plans.currentPlan': 'خطتك الحالية',
    'plans.active': 'نشط',
    'plans.feature1': 'أرباح يومية ثابتة',
    'plans.feature2': 'دعم فني 24/7',
    'plans.feature3': 'سحب الأرباح يومياً',
    'plans.importantInfo': 'معلومات مهمة',
    'plans.info1': 'عند شراء خطة، تختفي جميع الخطط الأقل منها',
    'plans.info2': 'ترقية تلقائية: إذا وصل المبلغ الكلي لقيمة الخطة الأعلى ولم يتم السحب، تتم الترقية تلقائياً',
    'plans.info3': 'ترقية يدوية: يمكن الترقية عبر إيداع المبلغ المطلوب للخطة الأعلى',
    'plans.info4': 'جميع الأرباح تضاف إلى المبلغ الكلي وتكون قابلة للسحب',
    
    // Profile page
    'profile.title': 'الملف الشخصي',
    'profile.personalInfo': 'المعلومات الشخصية',
    'profile.accountInfo': 'معلومات الحساب',
    'profile.edit': 'تعديل',
    'profile.save': 'حفظ',
    'profile.cancel': 'إلغاء',
    'profile.saving': 'جاري الحفظ...',
    'profile.success': 'تم حفظ التغييرات بنجاح',
    'profile.error': 'فشل في حفظ التغييرات',
    'profile.loading': 'جاري تحميل البيانات...',
    'profile.walletAddress': 'عنوان المحفظة',
    'profile.frozenBalance': 'المبلغ المجمد',
    'profile.frozenBalanceDesc': 'المبلغ المجمد للخطة الحالية',
    'profile.currentPlan': 'الخطة الحالية',
    'profile.memberSince': 'عضو منذ',
    'profile.lastLogin': 'آخر تسجيل دخول',
    'profile.security': 'الأمان',
    'profile.changePassword': 'تغيير كلمة المرور',
    'profile.twoFactor': 'المصادقة الثنائية',
    'profile.settings': 'الإعدادات',
    'profile.notifications': 'الإشعارات',
    'profile.language': 'اللغة',
    'profile.theme': 'المظهر',
    'profile.about': 'حول التطبيق',
    'profile.help': 'المساعدة',
    'profile.contact': 'اتصل بنا',
    'profile.logout': 'تسجيل الخروج',
    'profile.fullName': 'الاسم الكامل',
    'profile.phone': 'رقم الهاتف',
    'profile.email': 'البريد الإلكتروني',
    'profile.username': 'اسم المستخدم',
    'profile.referralCode': 'كود الإحالة',
    'profile.referralCodeCopied': 'تم نسخ كود الإحالة',
    'profile.walletAddressCopied': 'تم نسخ عنوان المحفظة',
    'profile.active': 'نشط',
    'profile.dailyProfit': 'الربح اليومي',
    'profile.actions': 'الإجراءات',
    'profile.contactSupport': 'التواصل مع الدعم',
    
    // Deposit page
    'deposit.title': 'إيداع الأموال',
    'deposit.description': 'أضف أموالك إلى حسابك للبدء في الاستثمار',
    'deposit.amount': 'المبلغ',
    'deposit.enterAmount': 'أدخل المبلغ',
    'deposit.minAmount': 'الحد الأدنى: 10 USDT',
    'deposit.maxAmount': 'الحد الأقصى: 10,000 USDT',
    'deposit.method': 'طريقة الدفع',
    'deposit.selectMethod': 'اختر طريقة الدفع',
    'deposit.crypto': 'العملات الرقمية',
    'deposit.bank': 'التحويل البنكي',
    'deposit.card': 'البطاقة الائتمانية',
    'deposit.wallet': 'المحفظة الإلكترونية',
    'deposit.address': 'عنوان الاستقبال',
    'deposit.copyAddress': 'نسخ العنوان',
    'deposit.qrCode': 'رمز QR',
    'deposit.confirm': 'تأكيد الإيداع',
    'deposit.processing': 'جاري المعالجة...',
    'deposit.success': 'تم إرسال طلب الإيداع بنجاح',
    'deposit.error': 'فشل في إرسال طلب الإيداع',
    'deposit.loading': 'جاري التحميل...',
    'deposit.history': 'سجل الإيداعات',
    'deposit.noHistory': 'لا توجد إيداعات سابقة',
    'deposit.loadAddressError': 'فشل في تحميل عنوان الإيداع',
    'deposit.loadingAddress': 'جاري تحميل عنوان الإيداع...',
    'deposit.depositAmount': 'مبلغ الإيداع',
    'deposit.clickToCopy': 'اضغط على الأيقونة لنسخ العنوان',
    'deposit.importantNotes': 'ملاحظات مهمة',
    'deposit.minDeposit': 'الحد الأدنى للإيداع',
    'deposit.trc20Only': 'شبكة TRC20 فقط - لا تستخدم شبكات أخرى',
    'deposit.singleAddress': 'عنوان الإيداع واحد فقط ويمكن تغييره من لوحة التحكم',
    'deposit.verifyAddress': 'تأكد من صحة العنوان قبل الإرسال',
    'deposit.confirmationTime': 'قد تستغرق المعاملة من 5-30 دقيقة للتأكيد',
    'deposit.recentDeposits': 'آخر الإيداعات',
    'deposit.twoHoursAgo': 'منذ ساعتين',
    'deposit.fiveHoursAgo': 'منذ 5 ساعات',
    'deposit.transactionHash': 'رمز المعاملة',
    'deposit.enterTransactionHash': 'أدخل رمز المعاملة (اختياري)',
    'deposit.transactionHashHelp': 'يمكنك إضافة رمز المعاملة الآن أو لاحقاً من سجل الإيداعات',
    'deposit.firstDepositBonus.title': 'مكافأة أول إيداع 10%',
    'deposit.firstDepositBonus.description': 'احصل على مكافأة 10% على أول إيداع لك! سيتم إضافة المكافأة تلقائياً عند تأكيد الإيداع من قبل الإدارة.',
    'deposit.firstDepositBonus.youWillGet': 'ستحصل على',
    'deposit.firstDepositBonus.note': 'المكافأة تُضاف تلقائياً عند تأكيد الإيداع',
    
    // Withdraw page
    'withdraw.title': 'سحب الأموال',
    'withdraw.description': 'اسحب أموالك من حسابك',
    'withdraw.amount': 'المبلغ',
    'withdraw.enterAmount': 'أدخل المبلغ',
    'withdraw.available': 'المتاح للسحب',
    'withdraw.minAmount': 'الحد الأدنى: 10 USDT',
    'withdraw.maxAmount': 'الحد الأقصى: 5,000 USDT',
    'withdraw.method': 'طريقة السحب',
    'withdraw.selectMethod': 'اختر طريقة السحب',
    'withdraw.address': 'عنوان المحفظة',
    'withdraw.enterAddress': 'أدخل عنوان المحفظة',
    'withdraw.confirm': 'تأكيد السحب',
    'withdraw.processing': 'جاري المعالجة...',
    'withdraw.success': 'تم إرسال طلب السحب بنجاح',
    'withdraw.error': 'فشل في إرسال طلب السحب',
    'withdraw.loading': 'جاري التحميل...',
    'withdraw.history': 'سجل السحوبات',
    'withdraw.noHistory': 'لا توجد سحوبات سابقة',
    'withdraw.fee': 'رسوم السحب',
    'withdraw.netAmount': 'المبلغ الصافي',
    'withdraw.profitsOnly': 'الأرباح فقط - رأس المال غير قابل للسحب',
    'withdraw.newRequest': 'طلب سحب جديد',
    'withdraw.requestedAmount': 'المبلغ المطلوب',
    'withdraw.insufficientBalance': 'رصيدك غير كافي للسحب',
    'withdraw.noWalletAddress': 'لم يتم تعيين عنوان المحفظة',
    'withdraw.walletAddressFixed': 'عنوان المحفظة ثابت ولا يمكن تغييره إلا من قبل الدعم أو لوحة التحكم',
    'withdraw.net': 'صافي',
    'withdraw.importantInfo': 'معلومات مهمة',
    'withdraw.minWithdrawal': 'الحد الأدنى للسحب',
    'withdraw.withdrawalFee': 'رسوم السحب',
    'withdraw.deductedAutomatically': 'تخصم تلقائياً',
    'withdraw.noWithdrawalIfPending': 'لا يمكن السحب إذا كان هناك طلب معلق',
    'withdraw.processingTime': 'مدة التنفيذ',
    'withdraw.hours': 'ساعة',
    
    // Team page
    'team.title': 'فريقي',
    'team.description': 'إدارة فريق الإحالة الخاص بك',
    'team.stats': 'إحصائيات الفريق',
    'team.totalMembers': 'إجمالي الأعضاء',
    'team.activeMembers': 'الأعضاء النشطون',
    'team.totalEarnings': 'إجمالي الأرباح',
    'team.monthlyEarnings': 'أرباح الشهر',
    'team.referralLink': 'رابط الإحالة',
    'team.copyLink': 'نسخ الرابط',
    'team.members': 'الأعضاء',
    'team.noMembers': 'لا يوجد أعضاء في فريقك بعد',
    'team.inviteFriends': 'ادع أصدقاءك',
    'team.loading': 'جاري تحميل بيانات الفريق...',
    'team.memberName': 'اسم العضو',
    'team.joinDate': 'تاريخ الانضمام',
    'team.status': 'الحالة',
    'team.earnings': 'الأرباح',
    'team.active': 'نشط',
    'team.inactive': 'غير نشط',
    'team.level': 'المستوى',
    'team.directMembers': 'المباشرون',
    'team.indirectMembers': 'غير المباشرين',
    'team.referralSystem': 'نظام الإحالة',
    'team.level1': 'المستوى الأول',
    'team.level2': 'المستوى الثاني',
    'team.direct': 'مباشر',
    'team.indirect': 'غير مباشر',
    'team.unknownMember': 'عضو غير معروف',
    'team.joinedOn': 'انضم في',
    'team.undefined': 'غير محدد',
    'team.noDirectMembers': 'لا يوجد أعضاء مباشرين بعد',
    'team.shareReferralCode': 'شارك كود الإحالة الخاص بك لجذب أعضاء جدد',
    'team.noIndirectMembers': 'لا يوجد أعضاء غير مباشرين',
    'team.indirectMembersDesc': 'سيظهرون عندما يجذب أعضاؤك المباشرون أعضاء جدد',
    'team.importantInfo': 'معلومات مهمة',
    'team.level1Info': 'المستوى الأول (مباشر): 12% من إيداعاتهم',
    'team.level2Info': 'المستوى الثاني (غير مباشر): 6% من إيداعاتهم',
    'team.earningsInfo': 'الأرباح تضاف فوراً وقابلة للسحب',
    'team.privacyInfo': 'أسماء غير المباشرين مخفية جزئياً لحماية الخصوصية',
    'team.unlimitedMembers': 'كل عضو يمكنه جذب عدد غير محدود من الأعضاء',
    
    // Promo page
    'promo.title': 'الكود الترويجي',
    'promo.description': 'استخدم الأكواد الترويجية للحصول على مكافآت إضافية',
    'promo.enterCode': 'أدخل الكود الترويجي',
    'promo.apply': 'تطبيق',
    'promo.applying': 'جاري التطبيق...',
    'promo.success': 'تم تطبيق الكود بنجاح',
    'promo.error': 'فشل في تطبيق الكود',
    'promo.invalid': 'كود غير صحيح',
    'promo.expired': 'كود منتهي الصلاحية',
    'promo.used': 'كود مستخدم مسبقاً',
    'promo.reward': 'المكافأة',
    'promo.discount': 'خصم',
    'promo.bonus': 'مكافأة إضافية',
    'promo.history': 'سجل الأكواد المستخدمة',
    'promo.noHistory': 'لا توجد أكواد مستخدمة',
    'promo.loading': 'جاري التحميل...',
    'promo.code': 'الكود',
    'promo.date': 'التاريخ',
    'promo.value': 'القيمة',
    'promo.activateTitle': 'تفعيل الكود الترويجي',
    'promo.activateDescription': 'أدخل الكود الترويجي للحصول على مكافأة خاصة',
    'promo.enterCodeError': 'يرجى إدخال الكود الترويجي',
    'promo.activationSuccess': 'تم تفعيل الكود بنجاح! المكافأة: {reward} USDT',
    'promo.activationError': 'فشل في تفعيل الكود الترويجي',
    'promo.activating': 'جاري التفعيل...',
    'promo.activate': 'تفعيل الكود',
    'promo.activated': 'مفعل',
    'promo.noHistoryDesc': 'قم بتفعيل كود ترويجي للحصول على مكافأة',
    'promo.infoTitle': 'معلومات مهمة',
    'promo.infoOneTime': 'يمكن تفعيل الكود الترويجي مرة واحدة فقط',
    'promo.infoFullActivation': 'بعض الأكواد قد تفعل الحساب كاملاً بدون إيداع',
    'promo.infoContests': 'الأكواد الترويجية من مسابقات أو عروض خاصة',
    'promo.infoImmediate': 'المكافآت تضاف فوراً إلى رصيدك',
    'promo.infoKeepSafe': 'احتفظ بالأكواد الترويجية في مكان آمن',
    'promo.specialOffers': 'عروض خاصة',
    'promo.welcomeOffer': 'عرض الترحيب',
    'promo.new': 'جديد',
    'promo.welcomeOfferDesc': 'احصل على 50 USDT مجاناً عند التسجيل باستخدام كود ترحيب صالح',
    'promo.newUsersOnly': 'متاح للمستخدمين الجدد فقط',
    'promo.referralOffer': 'عرض الإحالة',
    'promo.limited': 'محدود',
    'promo.referralOfferDesc': 'احصل على 25 USDT لكل 5 أعضاء جدد تجذبهم باستخدام كود الإحالة',
    'promo.limitedTime': 'عرض محدود الوقت',
    
    // Community page
    'community.title': 'المجتمع',
    'community.description': 'تواصل مع أعضاء المجتمع',
    'community.chat': 'المحادثة العامة',
    'community.enterMessage': 'أدخل رسالتك...',
    'community.send': 'إرسال',
    'community.sending': 'جاري الإرسال...',
    'community.loading': 'جاري تحميل الرسائل...',
    'community.loadingMore': 'جاري تحميل المزيد...',
    'community.noMessages': 'لا توجد رسائل',
    'community.online': 'متصل',
    'community.offline': 'غير متصل',
    'community.realTime': 'وقت حقيقي',
    'community.connecting': 'جاري الاتصال',
    'community.members': 'الأعضاء المتصلون',
    'community.noMembers': 'لا يوجد أعضاء متصلون',
    'community.rules': 'قواعد المجتمع',
    'community.beRespectful': 'كن محترماً',
    'community.noSpam': 'لا للرسائل المزعجة',
    'community.noAdvertising': 'لا للإعلانات',
    'community.report': 'إبلاغ',
    'community.block': 'حظر',
    'community.unblock': 'إلغاء الحظر',
    'community.admin': 'مدير',
    'community.pinned': 'الرسائل المثبتة',
    'community.adminMessages': 'رسائل الإدارة',
    'community.userMessages': 'رسائل المستخدمين',
    'community.pin': 'تثبيت',
    'community.unpin': 'إلغاء التثبيت',
    'community.like': 'إعجاب',
    'community.dislike': 'عدم إعجاب',
    'community.reacted': 'تم التفاعل',
    'community.removeReaction': 'اضغط لإزالة التفاعل',
    'community.messageSent': 'تم إرسال الرسالة بنجاح!',
    'community.sendError': 'حدث خطأ أثناء إرسال الرسالة',
    'community.loadError': 'حدث خطأ أثناء تحميل الرسائل',
    'community.scrollToTop': 'العودة للأعلى',
    
    // Support page
    'support.title': 'الدعم الفني',
    'support.description': 'نحن هنا لمساعدتك',
    'support.contact': 'اتصل بنا',
    'support.email': 'البريد الإلكتروني',
    'support.phone': 'الهاتف',
    'support.whatsapp': 'واتساب',
    'support.telegram': 'تليجرام',
    'support.liveChat': 'المحادثة المباشرة',
    'support.faq': 'الأسئلة الشائعة',
    'support.loading': 'جاري تحميل الرسائل...',
    'support.sendMessage': 'إرسال رسالة',
    'support.subject': 'الموضوع',
    'support.message': 'الرسالة',
    'support.enterSubject': 'أدخل الموضوع',
    'support.enterMessage': 'أدخل رسالتك',
    'support.sending': 'جاري الإرسال...',
    'support.success': 'تم إرسال الرسالة بنجاح',
    'support.error': 'فشل في إرسال الرسالة',
    'support.workingHours': 'ساعات العمل',
    'support.available': 'متاح 24/7',
    'support.welcome': 'مرحباً بك في الدعم الفني',
    'support.welcomeMessage': 'نحن هنا لمساعدتك في أي مشكلة تواجهها. يمكنك إرسال رسالة وسيتم الرد عليك في أقرب وقت ممكن.',
    'support.supportTeam': 'الدعم الفني',
    'support.new': 'جديد',
    'support.loadError': 'فشل في تحميل الرسائل',
    'support.sendError': 'فشل في إرسال الرسالة',
    'support.infoTitle': 'معلومات الدعم الفني',
    'support.responseTime': 'وقت الاستجابة: خلال 24 ساعة',
    'support.createTicket': 'إنشاء تذكرة جديدة',
    'support.cancel': 'إلغاء',
    'support.newTicket': 'تذكرة جديدة',
    'support.subjectPlaceholder': 'أدخل عنوان التذكرة',
    'support.descriptionPlaceholder': 'اشرح مشكلتك بالتفصيل',
    'support.create': 'إنشاء التذكرة',
    'support.creating': 'جاري الإنشاء...',
    'support.createError': 'فشل في إنشاء التذكرة',
    'support.noTickets': 'لا توجد تذاكر',
    'support.noTicketsMessage': 'لم تقم بإنشاء أي تذكرة دعم فني بعد. يمكنك إنشاء تذكرة جديدة للحصول على المساعدة.',
    'support.createFirstTicket': 'إنشاء أول تذكرة',
    'support.messages': 'رسائل',
    'support.anytimeMessage': 'يمكنك إرسال رسائل في أي وقت وسيتم الرد عليها',
    'support.urgentContact': 'للمشاكل العاجلة، يرجى الاتصال على: +966-XX-XXX-XXXX',
    
    // Promo Codes
    'promo.title': 'الأكواد الترويجية',
    'promo.activateTitle': 'تفعيل كود ترويجي',
    'promo.activateDescription': 'أدخل الكود الترويجي للحصول على مكافآت خاصة',
    'promo.code': 'الكود الترويجي',
    'promo.enterCode': 'أدخل الكود هنا',
    'promo.enterCodeError': 'يرجى إدخال كود ترويجي',
    'promo.activate': 'تفعيل الكود',
    'promo.activating': 'جاري التفعيل...',
    'promo.activationSuccess': 'تم تفعيل الكود الترويجي بنجاح',
    'promo.activationError': 'فشل في تفعيل الكود الترويجي',
    'promo.history': 'سجل الأكواد المستخدمة',
    'promo.activated': 'مفعل',
    'promo.noHistory': 'لا توجد أكواد مستخدمة',
    'promo.noHistoryDesc': 'لم تقم بتفعيل أي كود ترويجي بعد',
    'promo.infoTitle': 'معلومات الأكواد الترويجية',
    'promo.infoOneTime': 'يمكن استخدام كل كود ترويجي مرة واحدة فقط لكل مستخدم',
    'promo.infoFullActivation': 'تفعيل كامل للحساب مع مكافآت إضافية',
    'promo.infoContests': 'أكواد خاصة من المسابقات والمناسبات',
    'promo.infoImmediate': 'تطبيق فوري للمكافآت على رصيدك',
    'promo.infoKeepSafe': 'احتفظ بأكوادك الترويجية في مكان آمن',
    'promo.specialOffers': 'العروض الخاصة',
    'promo.welcomeOffer': 'عرض الترحيب',
    'promo.new': 'جديد',
    'promo.welcomeOfferDesc': 'كود ترحيبي للمستخدمين الجدد مع مكافأة 50 USDT',
    'promo.newUsersOnly': 'للمستخدمين الجدد فقط',
    'promo.referralOffer': 'عرض الإحالة',
    'promo.limited': 'محدود',
    'promo.referralOfferDesc': 'مكافآت إضافية عند إحالة أصدقائك',
    'promo.limitedTime': 'عرض محدود الوقت',
    
    // Transactions page
    'transactions.title': 'المعاملات',
    'transactions.description': 'سجل جميع معاملاتك',
    'transactions.all': 'الكل',
    'transactions.deposits': 'الإيداعات',
    'transactions.withdrawals': 'السحوبات',
    'transactions.earnings': 'الأرباح',
    'transactions.referrals': 'الإحالات',
    'transactions.date': 'التاريخ',
    'transactions.amount': 'المبلغ',
    'transactions.type': 'النوع',
    'transactions.status': 'الحالة',
    'transactions.pending': 'قيد الانتظار',
    'transactions.completed': 'مكتملة',
    'transactions.failed': 'فشلت',
    'transactions.cancelled': 'ملغية',
    'transactions.noTransactions': 'لا توجد معاملات',
    'transactions.loading': 'جاري تحميل المعاملات...',
    'transactions.details': 'التفاصيل',
    'transactions.transactionId': 'رقم المعاملة',
    'transactions.fee': 'الرسوم',
    'transactions.netAmount': 'المبلغ الصافي',
    
    // Notifications
    'notifications.title': 'الإشعارات',
    'notifications.unread': 'إشعار جديد',
    'notifications.unreadCount': 'إشعار جديد من أصل',
    'notifications.markAsRead': 'تحديد كمقروء',
    'notifications.markAllAsRead': 'تحديد الكل كمقروء',
    'notifications.noNotifications': 'لا توجد إشعارات',
    'notifications.noNotificationsDesc': 'لا توجد إشعارات جديدة. ستظهر هنا عندما تتلقى إشعارات جديدة.',
    'notifications.loading': 'جاري تحميل الإشعارات...',
    'notifications.taskCompleted': 'تم إكمال المهمة بنجاح',
    'notifications.newTask': 'مهمة جديدة متاحة',
    'notifications.depositSuccess': 'تم إيداع المبلغ',
    'notifications.teamMember': 'عضو جديد في الفريق',
    'notifications.systemUpdate': 'تحديث النظام',
    
    // Common
    'common.loading': 'جاري التحميل...',
    'common.error': 'حدث خطأ',
    'common.success': 'تم بنجاح',
    'common.cancel': 'إلغاء',
    'common.confirm': 'تأكيد',
    'common.save': 'حفظ',
    'common.edit': 'تعديل',
    'common.delete': 'حذف',
    'common.close': 'إغلاق',
    'common.back': 'العودة',
    'common.next': 'التالي',
    'common.previous': 'السابق',
    'common.submit': 'إرسال',
    'common.search': 'بحث',
    'common.filter': 'تصفية',
    'common.sort': 'ترتيب',
    'common.refresh': 'تحديث',
    'common.retry': 'إعادة المحاولة',
    'common.yes': 'نعم',
    'common.no': 'لا',
    'common.ok': 'موافق',
    'common.copy': 'نسخ',
    'common.copied': 'تم النسخ',
    'common.download': 'تحميل',
    'common.upload': 'رفع',
    'common.view': 'عرض',
    'common.details': 'التفاصيل',
    'common.more': 'المزيد',
    'common.less': 'أقل',
    'common.all': 'الكل',
    'common.none': 'لا شيء',
    'common.select': 'اختيار',
    'common.required': 'مطلوب',
    'common.optional': 'اختياري',
    'common.invalid': 'غير صحيح',
    'common.valid': 'صحيح',
    'common.of': 'من',
    'common.unknown': 'غير معروف',
    'common.undefined': 'غير محدد',
    'common.viewAll': 'عرض الكل',
    
    // Language
    'language.arabic': 'العربية',
    'language.english': 'English',
    'language.switch': 'تبديل اللغة',
    'language.current': 'اللغة الحالية',
  },
  en: {
    // Landing page
    'landing.title': 'PROMOXA',
    'landing.subtitle': 'Advanced Digital Currency Platform',
    'landing.description': 'Join our community and earn daily profits through simple tasks',
    'landing.features.title': 'Features',
    'landing.features.daily': 'Daily Earnings',
    'landing.features.referral': 'Advanced Referral System',
    'landing.features.support': '24/7 Support',
    'landing.features.secure': 'High Security',
    'landing.getStarted': 'Get Started',
    'landing.login': 'Login',
    'landing.register': 'Register',
    
    // Home page
    'home.title': 'Home',
    'home.welcome': 'Welcome to PROMOXA',
    'home.totalBalance': 'Available Balance',
    'home.totalProfit': 'Total Profit',
    'home.frozenBalance': 'Frozen Balance',
    'home.referralEarnings': 'Referral Earnings',
    'home.dailyEarnings': 'Daily Earnings',
    'home.totalEarnings': 'Total Earnings',
    'home.startDailyTasks': 'Start Daily Tasks Now',
    'home.operations': 'Operations',
    'home.orders': 'Daily Orders',
    'home.withdraw': 'Withdraw',
    'home.deposit': 'Deposit',
    'home.team': 'Team',
    'home.support': 'Support',
    'home.promoCode': 'Promo Code',
    'home.plans': 'Plans',
    'home.community': 'Community',
    'home.news': 'Latest News',
    'home.news.feature': 'New community feature launched',
    'home.news.update': 'System update for better performance',
    'home.news.offers': 'Special offers for Gold Plan',
    'home.news.2hoursAgo': '2 hours ago',
    'home.news.1dayAgo': '1 day ago',
    'home.news.3daysAgo': '3 days ago',
    'home.referralCode': 'Referral Code',
    'home.copySuccess': 'Copied!',
    'home.demoMode': 'You are in demo mode - Data is not real',
    'home.loading': 'Loading data...',
    'home.user': 'User',
    'home.back': 'Back',
    'home.logout': 'Logout',
    'home.notifications': 'Notifications',
    'home.language': 'Language',
    'home.profile': 'Profile',
    
    // Auth pages
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.logout': 'Logout',
    'auth.username': 'Username',
    'auth.usernameOrPhone': 'Username or Phone',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.email': 'Email',
    'auth.phone': 'Phone Number',
    'auth.fullName': 'Full Name',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.noAccount': "Don't have an account?",
    'auth.haveAccount': 'Already have an account?',
    'auth.createAccount': 'Create New Account',
    'auth.loginToAccount': 'Login to your account',
    'auth.registerAccount': 'Create New Account',
    'auth.loginSuccess': 'Login successful',
    'auth.loginError': 'Login failed',
    'auth.registerSuccess': 'Account created successfully',
    'auth.registerError': 'Account creation failed',
    'auth.passwordsNotMatch': 'Passwords do not match',
    'auth.invalidCredentials': 'Invalid credentials',
    'auth.serverError': 'Server error',
    'auth.networkError': 'Network error',
    'auth.demoMode': 'Demo Mode',
    'auth.demoDescription': 'Backend server is not available. You can try the frontend in demo mode.',
    'auth.tryDemo': 'Try Demo Mode',
    'auth.enterUsername': 'Enter username or phone',
    'auth.enterPassword': 'Enter password',
    'auth.enterEmail': 'Enter email',
    'auth.enterPhone': 'Enter phone number',
    'auth.enterFullName': 'Enter full name',
    'auth.enterConfirmPassword': 'Enter confirm password',
    'auth.loginButton': 'Login',
    'auth.registerButton': 'Register',
    'auth.loggingIn': 'Logging in...',
    'auth.registering': 'Creating account...',
    
    // Forgot Password page
    'forgotPassword.title': 'Reset Password',
    'forgotPassword.enterEmailDescription': 'Enter your email to send verification code',
    'forgotPassword.email': 'Email',
    'forgotPassword.enterEmail': 'Enter your email',
    'forgotPassword.sendOtp': 'Send Verification Code',
    'forgotPassword.sending': 'Sending...',
    'forgotPassword.sentSuccessfully': 'Sent Successfully!',
    'forgotPassword.otpSentMessage': 'Verification code has been sent to your email',
    'forgotPassword.tryAgain': 'Try Again',
    'forgotPassword.backToLogin': 'Back to Login',
    'forgotPassword.importantInfo': 'Important Information',
    'forgotPassword.info1Email': 'Make sure to enter the email registered in your account',
    'forgotPassword.info2Otp': 'Verification code is valid for 10 minutes only',
    'forgotPassword.info3Email': 'If you did not receive the code, check your spam folder',
    'forgotPassword.info4': 'For additional help, contact technical support',
    
    // Orders page
    'orders.title': 'Daily Orders',
    'orders.status': 'Daily Tasks Status',
    'orders.completed': 'Completed',
    'orders.progress': 'Progress',
    'orders.openTime': 'Tasks Open Time',
    'orders.openTimeDesc': 'Daily tasks open at 7:00 PM server time',
    'orders.completeTask': 'Complete Task',
    'orders.complete': 'Complete',
    'orders.taskCompleted': 'Task completed successfully!',
    'orders.completing': 'Completing...',
    'orders.noTasks': 'No tasks available',
    'orders.noTasksDesc': 'No tasks available currently. Check back later for new tasks.',
    'orders.closedDesc': 'Tasks are currently closed. They open at 7:00 PM server time.',
    'orders.loading': 'Loading tasks...',
    'orders.error': 'Error loading tasks',
    'orders.success': 'Task completed successfully!',
    'orders.failed': 'Failed to complete task',
    'orders.open': 'Open',
    'orders.closed': 'Closed',
    'orders.taskTitle': 'Task Title',
    'orders.taskDescription': 'Task Description',
    'orders.taskProfit': 'Task Profit',
    'orders.infoTitle': 'Task Info',
    'orders.infoDesc1': 'Daily tasks open at 7:00 PM server time',
    'orders.infoDesc2': '5 daily tasks per user',
    'orders.infoDesc3': 'After completing all tasks, buttons will be disabled until the next day',
    'orders.infoDesc4': 'Task list updates weekly',
    'orders.infoDesc5': 'Earnings are added immediately to your balance',
    'orders.infoDesc6': 'Tasks refresh daily at 7:00 AM server time',
    'orders.today': 'Today',
    'orders.todayTasks': 'Today\'s Tasks',
    'orders.thisWeek': 'This Week',
    'orders.noTasksToday': 'No tasks completed today',
    'orders.noTasksThisWeek': 'No tasks completed this week',
    'orders.totalEarnings': 'Total Earnings',
    'orders.noPlanTitle': 'No Active Plan',
    'orders.noPlanMessage': 'You need to purchase a plan to access daily tasks',
    'orders.getPlan': 'Get Plan',
    
    // Task Descriptions - English translations
    'task.description.1': 'You supported a marketing campaign for an online store.',
    'task.description.2': 'You promoted a new mobile application.',
    'task.description.3': 'You contributed to a renewable energy project.',
    'task.description.4': 'You helped boost an online ad campaign.',
    'task.description.5': 'You participated in a social media promotion.',
    'task.description.6': 'You assisted in launching a new e-commerce shop.',
    'task.description.7': 'You supported an influencer\'s ad campaign.',
    'task.description.8': 'You helped advertise eco-friendly products.',
    'task.description.9': 'You contributed to digital marketing for a startup.',
    'task.description.10': 'You promoted an online learning platform.',
    'task.description.11': 'You supported an awareness campaign for recycling.',
    'task.description.12': 'You boosted an advertising campaign for a clothing brand.',
    'task.description.13': 'You promoted an online gaming platform.',
    'task.description.14': 'You assisted in a crypto project campaign.',
    'task.description.15': 'You supported a campaign for a travel agency.',
    'task.description.16': 'You promoted a new food delivery app.',
    'task.description.17': 'You boosted marketing for a fitness brand.',
    'task.description.18': 'You contributed to an advertisement for electronics.',
    'task.description.19': 'You promoted a campaign for smart home devices.',
    'task.description.20': 'You supported a fundraising campaign for startups.',
    'task.description.21': 'You boosted a marketing push for digital services.',
    'task.description.22': 'You helped promote sustainable agriculture.',
    'task.description.23': 'You assisted in advertising new fashion items.',
    'task.description.24': 'You supported an online investment project.',
    'task.description.25': 'You promoted a new subscription service.',
    'task.description.26': 'You boosted traffic for an educational campaign.',
    'task.description.27': 'You contributed to an ad campaign for green energy.',
    'task.description.28': 'You promoted an innovative tech gadget.',
    'task.description.29': 'You assisted in growing an e-commerce platform.',
    'task.description.30': 'You supported online awareness for data security.',
    'task.description.31': 'You boosted visibility of a charity initiative.',
    'task.description.32': 'You promoted a digital artwork platform.',
    'task.description.33': 'You assisted in spreading an app for freelancers.',
    'task.description.34': 'You supported a campaign for mobile payments.',
    'task.description.35': 'You promoted new digital banking solutions.',
    'task.description.36': 'You boosted a promotion for healthcare products.',
    'task.description.37': 'You supported online marketing for music artists.',
    'task.description.38': 'You promoted a book publishing platform.',
    'task.description.39': 'You helped advertise a SaaS company.',
    'task.description.40': 'You contributed to spreading a new online course.',
    'task.description.41': 'You promoted an awareness campaign for clean water.',
    'task.description.42': 'You supported a campaign for eco-friendly fashion.',
    'task.description.43': 'You helped in an ad campaign for digital wallets.',
    'task.description.44': 'You boosted marketing for an AI tool.',
    'task.description.45': 'You promoted a startup crowdfunding campaign.',
    'task.description.46': 'You supported brand visibility for a food brand.',
    'task.description.47': 'You promoted an ad for sports equipment.',
    'task.description.48': 'You helped boost an online charity project.',
    'task.description.49': 'You contributed to a new product launch.',
    'task.description.50': 'You supported a campaign for cloud services.',
    
    // Plans page
    'plans.title': 'Investment Plans',
    'plans.description': 'Choose the plan that suits you and start investing',
    'plans.basic': 'Basic Plan',
    'plans.silver': 'Silver Plan',
    'plans.gold': 'Gold Plan',
    'plans.diamond': 'Diamond Plan',
    'plans.price': 'Price',
    'plans.dailyProfit': 'Daily Profit',
    'plans.duration': 'Duration',
    'plans.features': 'Features',
    'plans.buyNow': 'Buy Now',
    'plans.purchasing': 'Purchasing...',
    'plans.success': 'Plan purchased successfully!',
    'plans.error': 'Failed to purchase plan',
    'plans.loading': 'Loading plans...',
    'plans.days': 'days',
    'plans.min': 'Min',
    'plans.max': 'Max',
    'plans.usdt': 'USDT',
    'plans.currentPlan': 'Your Current Plan',
    'plans.active': 'Active',
    'plans.feature1': 'Fixed daily profits',
    'plans.feature2': '24/7 technical support',
    'plans.feature3': 'Daily profit withdrawal',
    'plans.importantInfo': 'Important Information',
    'plans.info1': 'When purchasing a plan, all lower plans disappear',
    'plans.info2': 'Automatic upgrade: If the total amount reaches the value of the higher plan and no withdrawal is made, upgrade happens automatically',
    'plans.info3': 'Manual upgrade: Can upgrade by depositing the required amount for the higher plan',
    'plans.info4': 'All profits are added to the total amount and are withdrawable',
    
    // Profile page
    'profile.title': 'Profile',
    'profile.personalInfo': 'Personal Information',
    'profile.accountInfo': 'Account Information',
    'profile.edit': 'Edit',
    'profile.save': 'Save',
    'profile.cancel': 'Cancel',
    'profile.saving': 'Saving...',
    'profile.success': 'Changes saved successfully',
    'profile.error': 'Failed to save changes',
    'profile.loading': 'Loading data...',
    'profile.walletAddress': 'Wallet Address',
    'profile.frozenBalance': 'Frozen Balance',
    'profile.frozenBalanceDesc': 'Amount frozen for current plan',
    'profile.currentPlan': 'Current Plan',
    'profile.memberSince': 'Member Since',
    'profile.lastLogin': 'Last Login',
    'profile.security': 'Security',
    'profile.changePassword': 'Change Password',
    'profile.twoFactor': 'Two-Factor Authentication',
    'profile.settings': 'Settings',
    'profile.notifications': 'Notifications',
    'profile.language': 'Language',
    'profile.theme': 'Theme',
    'profile.about': 'About',
    'profile.help': 'Help',
    'profile.contact': 'Contact Us',
    'profile.logout': 'Logout',
    'profile.fullName': 'Full Name',
    'profile.phone': 'Phone Number',
    'profile.email': 'Email',
    'profile.username': 'Username',
    'profile.referralCode': 'Referral Code',
    'profile.referralCodeCopied': 'Referral code copied',
    'profile.walletAddressCopied': 'Wallet address copied',
    'profile.active': 'Active',
    'profile.dailyProfit': 'Daily Profit',
    'profile.actions': 'Actions',
    'profile.contactSupport': 'Contact Support',
    
    // Deposit page
    'deposit.title': 'Deposit Funds',
    'deposit.description': 'Add funds to your account to start investing',
    'deposit.amount': 'Amount',
    'deposit.enterAmount': 'Enter amount',
    'deposit.minAmount': 'Minimum: 10 USDT',
    'deposit.maxAmount': 'Maximum: 10,000 USDT',
    'deposit.method': 'Payment Method',
    'deposit.selectMethod': 'Select payment method',
    'deposit.crypto': 'Cryptocurrency',
    'deposit.bank': 'Bank Transfer',
    'deposit.card': 'Credit Card',
    'deposit.wallet': 'E-Wallet',
    'deposit.address': 'Receiving Address',
    'deposit.copyAddress': 'Copy Address',
    'deposit.qrCode': 'QR Code',
    'deposit.confirm': 'Confirm Deposit',
    'deposit.processing': 'Processing...',
    'deposit.success': 'Deposit request sent successfully',
    'deposit.error': 'Failed to send deposit request',
    'deposit.loading': 'Loading...',
    'deposit.history': 'Deposit History',
    'deposit.noHistory': 'No deposit history',
    'deposit.loadAddressError': 'Failed to load deposit address',
    'deposit.loadingAddress': 'Loading deposit address...',
    'deposit.depositAmount': 'Deposit Amount',
    'deposit.clickToCopy': 'Click the icon to copy address',
    'deposit.importantNotes': 'Important Notes',
    'deposit.minDeposit': 'Minimum deposit',
    'deposit.trc20Only': 'TRC20 network only - do not use other networks',
    'deposit.singleAddress': 'Single deposit address that can be changed from admin panel',
    'deposit.verifyAddress': 'Verify address before sending',
    'deposit.confirmationTime': 'Transaction may take 5-30 minutes to confirm',
    'deposit.recentDeposits': 'Recent Deposits',
    'deposit.twoHoursAgo': '2 hours ago',
    'deposit.fiveHoursAgo': '5 hours ago',
    'deposit.transactionHash': 'Transaction Hash',
    'deposit.enterTransactionHash': 'Enter Transaction Hash (Optional)',
    'deposit.transactionHashHelp': 'You can add the transaction hash now or later from the deposit history',
    'deposit.firstDepositBonus.title': 'First Deposit 10% Bonus',
    'deposit.firstDepositBonus.description': 'Get a 10% bonus on your first deposit! The bonus will be automatically added when the deposit is confirmed by admin.',
    'deposit.firstDepositBonus.youWillGet': 'You will get',
    'deposit.firstDepositBonus.note': 'Bonus is automatically added when deposit is confirmed',
    
    // Withdraw page
    'withdraw.title': 'Withdraw Funds',
    'withdraw.description': 'Withdraw funds from your account',
    'withdraw.amount': 'Amount',
    'withdraw.enterAmount': 'Enter amount',
    'withdraw.available': 'Available for withdrawal',
    'withdraw.minAmount': 'Minimum: 10 USDT',
    'withdraw.maxAmount': 'Maximum: 5,000 USDT',
    'withdraw.method': 'Withdrawal Method',
    'withdraw.selectMethod': 'Select withdrawal method',
    'withdraw.address': 'Wallet Address',
    'withdraw.enterAddress': 'Enter wallet address',
    'withdraw.confirm': 'Confirm Withdrawal',
    'withdraw.processing': 'Processing...',
    'withdraw.success': 'Withdrawal request sent successfully',
    'withdraw.error': 'Failed to send withdrawal request',
    'withdraw.loading': 'Loading...',
    'withdraw.history': 'Withdrawal History',
    'withdraw.noHistory': 'No withdrawal history',
    'withdraw.fee': 'Withdrawal Fee',
    'withdraw.netAmount': 'Net Amount',
    'withdraw.profitsOnly': 'Profits only - Capital is not withdrawable',
    'withdraw.newRequest': 'New Withdrawal Request',
    'withdraw.requestedAmount': 'Requested Amount',
    'withdraw.insufficientBalance': 'Insufficient balance for withdrawal',
    'withdraw.noWalletAddress': 'No wallet address assigned',
    'withdraw.walletAddressFixed': 'Wallet address is fixed and cannot be changed except by support or admin panel',
    'withdraw.net': 'Net',
    'withdraw.importantInfo': 'Important Information',
    'withdraw.minWithdrawal': 'Minimum withdrawal',
    'withdraw.withdrawalFee': 'Withdrawal fee',
    'withdraw.deductedAutomatically': 'deducted automatically',
    'withdraw.noWithdrawalIfPending': 'Cannot withdraw if there is a pending request',
    'withdraw.processingTime': 'Processing time',
    'withdraw.hours': 'hours',
    
    // Team page
    'team.title': 'My Team',
    'team.description': 'Manage your referral team',
    'team.stats': 'Team Statistics',
    'team.totalMembers': 'Total Members',
    'team.activeMembers': 'Active Members',
    'team.totalEarnings': 'Total Earnings',
    'team.monthlyEarnings': 'Monthly Earnings',
    'team.referralLink': 'Referral Link',
    'team.copyLink': 'Copy Link',
    'team.members': 'Members',
    'team.noMembers': 'No members in your team yet',
    'team.inviteFriends': 'Invite Friends',
    'team.loading': 'Loading team data...',
    'team.memberName': 'Member Name',
    'team.joinDate': 'Join Date',
    'team.status': 'Status',
    'team.earnings': 'Earnings',
    'team.active': 'Active',
    'team.inactive': 'Inactive',
    'team.level': 'Level',
    'team.directMembers': 'Direct Members',
    'team.indirectMembers': 'Indirect Members',
    'team.referralSystem': 'Referral System',
    'team.level1': 'Level 1',
    'team.level2': 'Level 2',
    'team.direct': 'Direct',
    'team.indirect': 'Indirect',
    'team.unknownMember': 'Unknown Member',
    'team.joinedOn': 'Joined on',
    'team.undefined': 'Undefined',
    'team.noDirectMembers': 'No direct members yet',
    'team.shareReferralCode': 'Share your referral code to attract new members',
    'team.noIndirectMembers': 'No indirect members',
    'team.indirectMembersDesc': 'They will appear when your direct members attract new members',
    'team.importantInfo': 'Important Information',
    'team.level1Info': 'Level 1 (Direct): 12% of their deposits',
    'team.level2Info': 'Level 2 (Indirect): 6% of their deposits',
    'team.earningsInfo': 'Earnings are added immediately and withdrawable',
    'team.privacyInfo': 'Indirect member names are partially hidden for privacy protection',
    'team.unlimitedMembers': 'Each member can attract unlimited number of members',
    
    // Promo page
    'promo.title': 'Promo Code',
    'promo.description': 'Use promo codes to get additional rewards',
    'promo.enterCode': 'Enter promo code',
    'promo.apply': 'Apply',
    'promo.applying': 'Applying...',
    'promo.success': 'Code applied successfully',
    'promo.error': 'Failed to apply code',
    'promo.invalid': 'Invalid code',
    'promo.expired': 'Expired code',
    'promo.used': 'Code already used',
    'promo.reward': 'Reward',
    'promo.discount': 'Discount',
    'promo.bonus': 'Bonus',
    'promo.history': 'Used Codes History',
    'promo.noHistory': 'No used codes',
    'promo.loading': 'Loading...',
    'promo.code': 'Code',
    'promo.date': 'Date',
    'promo.value': 'Value',
    'promo.activateTitle': 'Activate Promo Code',
    'promo.activateDescription': 'Enter promo code to get a special reward',
    'promo.enterCodeError': 'Please enter a promo code',
    'promo.activationSuccess': 'Code activated successfully! Reward: {reward} USDT',
    'promo.activationError': 'Failed to activate promo code',
    'promo.activating': 'Activating...',
    'promo.activate': 'Activate Code',
    'promo.activated': 'Activated',
    'promo.noHistoryDesc': 'Activate a promo code to get a reward',
    'promo.infoTitle': 'Important Information',
    'promo.infoOneTime': 'Promo codes can only be activated once',
    'promo.infoFullActivation': 'Full account activation with bonus rewards',
    'promo.infoContests': 'Special codes from contests and events',
    'promo.infoImmediate': 'Instant application of rewards to your balance',
    'promo.infoKeepSafe': 'Keep your promo codes in a safe place',
    'promo.specialOffers': 'Special Offers',
    'promo.welcomeOffer': 'Welcome Offer',
    'promo.new': 'New',
    'promo.welcomeOfferDesc': 'Welcome code for new users with 50 USDT bonus',
    'promo.newUsersOnly': 'New users only',
    'promo.referralOffer': 'Referral Offer',
    'promo.limited': 'Limited',
    'promo.referralOfferDesc': 'Extra rewards when you refer friends',
    'promo.limitedTime': 'Limited time offer',
    
    // Community page
    'community.title': 'Community',
    'community.description': 'Connect with community members',
    'community.chat': 'Public Chat',
    'community.enterMessage': 'Enter your message...',
    'community.send': 'Send',
    'community.sending': 'Sending...',
    'community.loading': 'Loading messages...',
    'community.loadingMore': 'Loading more...',
    'community.noMessages': 'No messages',
    'community.online': 'Online',
    'community.offline': 'Offline',
    'community.realTime': 'Real-time',
    'community.connecting': 'Connecting',
    'community.members': 'Online Members',
    'community.noMembers': 'No online members',
    'community.rules': 'Community Rules',
    'community.beRespectful': 'Be respectful',
    'community.noSpam': 'No spam',
    'community.noAdvertising': 'No advertising',
    'community.report': 'Report',
    'community.block': 'Block',
    'community.unblock': 'Unblock',
    'community.admin': 'Admin',
    'community.pinned': 'Pinned Messages',
    'community.adminMessages': 'Admin Messages',
    'community.userMessages': 'User Messages',
    'community.pin': 'Pin',
    'community.unpin': 'Unpin',
    'community.like': 'Like',
    'community.dislike': 'Dislike',
    'community.reacted': 'Reacted',
    'community.removeReaction': 'Click to remove reaction',
    'community.messageSent': 'Message sent successfully!',
    'community.sendError': 'Error sending message',
    'community.loadError': 'Error loading messages',
    'community.scrollToTop': 'Back to top',
    
    // Support page
    'support.title': 'Support',
    'support.description': 'We are here to help you',
    'support.contact': 'Contact Us',
    'support.email': 'Email',
    'support.phone': 'Phone',
    'support.whatsapp': 'WhatsApp',
    'support.telegram': 'Telegram',
    'support.liveChat': 'Live Chat',
    'support.faq': 'FAQ',
    'support.loading': 'Loading...',
    'support.sendMessage': 'Send Message',
    'support.subject': 'Subject',
    'support.message': 'Message',
    'support.enterSubject': 'Enter subject',
    'support.enterMessage': 'Enter your message',
    'support.sending': 'Sending...',
    'support.success': 'Message sent successfully',
    'support.error': 'Failed to send message',
    'support.workingHours': 'Working Hours',
    'support.available': 'Available 24/7',
    'support.welcome': 'Welcome to Support',
    'support.welcomeMessage': 'We are here to help you with any issues you may face. You can send a message and we will respond as soon as possible.',
    'support.supportTeam': 'Support Team',
    'support.new': 'New',
    'support.loadError': 'Failed to load messages',
    'support.sendError': 'Failed to send message',
    'support.infoTitle': 'Support Information',
    'support.responseTime': 'Response time: Within 24 hours',
    'support.createTicket': 'Create New Ticket',
    'support.cancel': 'Cancel',
    'support.newTicket': 'New Ticket',
    'support.subjectPlaceholder': 'Enter ticket title',
    'support.descriptionPlaceholder': 'Describe your issue in detail',
    'support.create': 'Create Ticket',
    'support.creating': 'Creating...',
    'support.createError': 'Failed to create ticket',
    'support.noTickets': 'No Tickets',
    'support.noTicketsMessage': 'You haven\'t created any support tickets yet. You can create a new ticket to get help.',
    'support.createFirstTicket': 'Create First Ticket',
    'support.messages': 'messages',
    'support.anytimeMessage': 'You can send messages anytime and they will be responded to',
    'support.urgentContact': 'For urgent issues, please call: +966-XX-XXX-XXXX',
    
    // Notifications
    'notifications.title': 'Notifications',
    'notifications.unread': 'unread notification',
    'notifications.unreadCount': 'unread notification of',
    'notifications.markAsRead': 'Mark as Read',
    'notifications.markAllAsRead': 'Mark All as Read',
    'notifications.noNotifications': 'No Notifications',
    'notifications.noNotificationsDesc': 'No new notifications. They will appear here when you receive new notifications.',
    'notifications.loading': 'Loading notifications...',
    'notifications.taskCompleted': 'Task completed successfully',
    'notifications.newTask': 'New task available',
    'notifications.depositSuccess': 'Deposit successful',
    'notifications.teamMember': 'New team member',
    'notifications.systemUpdate': 'System update',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error occurred',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.close': 'Close',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.submit': 'Submit',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.refresh': 'Refresh',
    'common.retry': 'Retry',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.ok': 'OK',
    'common.copy': 'Copy',
    'common.copied': 'Copied',
    'common.download': 'Download',
    'common.upload': 'Upload',
    'common.view': 'View',
    'common.details': 'Details',
    'common.more': 'More',
    'common.less': 'Less',
    'common.all': 'All',
    'common.none': 'None',
    'common.select': 'Select',
    'common.required': 'Required',
    'common.optional': 'Optional',
    'common.invalid': 'Invalid',
    'common.valid': 'Valid',
    'common.of': 'of',
    'common.unknown': 'Unknown',
    'common.undefined': 'Undefined',
    'common.viewAll': 'View All',
    
    // Language
    'language.arabic': 'العربية',
    'language.english': 'English',
    'language.switch': 'Switch Language',
    'language.current': 'Current Language',
  }
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('ar')

  useEffect(() => {
    // Load language from localStorage on mount
    const savedLanguage = localStorage.getItem('language') as Language
    if (savedLanguage && (savedLanguage === 'ar' || savedLanguage === 'en')) {
      setLanguageState(savedLanguage)
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('language', lang)
    
    // Update document direction
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr'
    document.documentElement.lang = lang
  }

  const t = (key: string): string => {
    return (translations[language] as Record<string, string>)[key] || key
  }

  const isRTL = language === 'ar'

  // Set initial document direction
  useEffect(() => {
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr'
    document.documentElement.lang = language
  }, [language])

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
